config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "products#index"

  resources :products do
    collection do
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  #associations
  has_many :products
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  #validations
  validates :name, :code, :price, presence: true
  validates :code, uniqueness: true

  #associations
  belongs_to :category
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #enum      
  enum role: { 'Supplier': 0, 'Buyer': 1 }
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def new
  end

  def import
    result = Products::ImportProductsService.new(params).call!

    if result[:all_save] 
      redirect_to root_path
      flash[:notice]= "Successfully imported all Products"
    else
      redirect_to new_product_path 
      flash[:error] = result[:errors]
    end

  end

  def index
    @products = Products::FetchService.new(params).call!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_flash_messages.html.erb
<% if flash[:notice] %>
  <div class="flex items-center w-screen ms-[18%] p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
    <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <div>
      <span class="font-medium"><%= flash[:notice] %></span>
    </div>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="flex items-center w-screen ms-[18%] p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
    <svg class="flex-shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <% flash[:error].each do |error| %>
      <div>
        <span class="font-medium"><%= error %></span>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="w-screen sticky top-0 bg-[#FFFFFF] flex justify-start items-center border-b  h-[100px]">
  <p class="text-black  ps-[18%] text-2xl font-semibold">Dashboard</p>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="w-[15%] fixed top-0 flex flex-col justify-center items-center bg-gray-700 h-screen">
  <div class="h-[100px] flex items-center justify-center border-b w-full">
    <svg class="w-8 h-8 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 10V6a3 3 0 0 1 3-3v0a3 3 0 0 1 3 3v4m3-2 .917 11.923A1 1 0 0 1 17.92 21H6.08a1 1 0 0 1-.997-1.077L6 8h12Z"/>
    </svg>
    <p class="text-3xl ml-2 font-semibold text-gray-200">Horizon</p>
  </div>
  <div class="flex flex-col flex-1 gap-4 w-full  items-center text-center mt-5">
    <div class="w-full cursor-pointer relative  border border-gray-700 p-3 flex justify-center hover:border-gray-100 hover:bg-gray-600">
      <svg class="w-8 h-8 absolute left-10 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.143 4H4.857A.857.857 0 0 0 4 4.857v4.286c0 .473.384.857.857.857h4.286A.857.857 0 0 0 10 9.143V4.857A.857.857 0 0 0 9.143 4Zm10 0h-4.286a.857.857 0 0 0-.857.857v4.286c0 .473.384.857.857.857h4.286A.857.857 0 0 0 20 9.143V4.857A.857.857 0 0 0 19.143 4Zm-10 10H4.857a.857.857 0 0 0-.857.857v4.286c0 .473.384.857.857.857h4.286a.857.857 0 0 0 .857-.857v-4.286A.857.857 0 0 0 9.143 14Zm10 0h-4.286a.857.857 0 0 0-.857.857v4.286c0 .473.384.857.857.857h4.286a.857.857 0 0 0 .857-.857v-4.286a.857.857 0 0 0-.857-.857Z"/>
      </svg>
      <%= link_to "All Products", root_path, class:"text-xl font-medium text-gray-200 w-full" %>
    </div>
    <div class="w-full cursor-pointer relative flex border border-gray-700 p-3 justify-center gap-2  hover:border-gray-100 hover:bg-gray-600">
      <svg class="w-8 h-8 absolute left-10 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
        <path fill-rule="evenodd" d="M11.32 6.176H5c-1.105 0-2 .949-2 2.118v10.588C3 20.052 3.895 21 5 21h11c1.105 0 2-.948 2-2.118v-7.75l-3.914 4.144A2.46 2.46 0 0 1 12.81 16l-2.681.568c-1.75.37-3.292-1.263-2.942-3.115l.536-2.839c.097-.512.335-.983.684-1.352l2.914-3.086Z" clip-rule="evenodd"/>
        <path fill-rule="evenodd" d="M19.846 4.318a2.148 2.148 0 0 0-.437-.692 2.014 2.014 0 0 0-.654-.463 1.92 1.92 0 0 0-1.544 0 2.014 2.014 0 0 0-.654.463l-.546.578 2.852 3.02.546-.579a2.14 2.14 0 0 0 .437-.692 2.244 2.244 0 0 0 0-1.635ZM17.45 8.721 14.597 5.7 9.82 10.76a.54.54 0 0 0-.137.27l-.536 2.84c-.07.37.239.696.588.622l2.682-.567a.492.492 0 0 0 .255-.145l4.778-5.06Z" clip-rule="evenodd"/>
      </svg>
      <%= link_to "Add Product", new_product_path, class:"text-xl font-medium text-gray-200 w-full" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HorizonApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <style>
    body {
    width: 100%;
    height: 100%;
    overflow-x: hidden;
    }
  </style>
  <body class="overflow-none">
    <main class="container relative">
      <%= render 'layouts/header' %>
      <%= render 'layouts/sidebar' %>
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/products/index.html.erb
<section class="sm:p-5 w-full absolute left-[20%] top-[200px]">
  <div class="mx-auto max-w-full lg:px-12">
    <div class="bg-[#FAF9F6] border-2  relative shadow-md sm:rounded-lg overflow-hidden">
      <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
        <div class="w-full md:w-1/2">
          <%= form_with(url: products_path, method: "get", data: { turbo: false }, class: "flex items-center") do |f| %>
            <label for="simple-search" class="sr-only">Search</label>
            <div class="relative w-full">
              <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                <svg aria-hidden="true" class="w-5 h-5 text-[#232b2b]" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                </svg>
              </div>
              <%= f.text_field :search_key, id: "simple-search", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full pl-10 p-2", placeholder: "Search by product name or code ", required: true %>
            </div>
            <%= f.submit "Search", class: "ml-2 bg-primary-700 text-black cursor-pointer border bg-slate-400 rounded-lg px-4 py-2" %>
          <% end %>
        </div>
        <div class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
          <button  type="button" class="flex items-center justify-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2">
            <%= link_to "Add Product", new_product_path, class:"underline" %>
          </button>
          <div class="flex items-center space-x-3 w-full md:w-auto">
            <%# filter button %>
            <div class="flex">
              <%= form_with(url: products_path, method: "get", data: { controller: "filter" }) do |f| %>
                <div class="relative">
                  <%= f.collection_select(:category, Category.all, :id, :name, { include_blank: 'Filter by category' }, class: "w-full cursor-pointer md:w-auto flex items-center justify-center py-2 px-4 text-sm font-medium text-gray-200 focus:outline-none bg-gray-700 hover:bg-gray-600 rounded-lg border border-gray-200",data: { target: "filter.category", action: "change->filter#category" }) %>
                </div>
              </div>
            </div>
            <div>
              <%= f.submit "Apply filter", class:"hidden" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="overflow-x-auto">
        <table class="w-full text-sm text-left text-[#232b2b]">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" class="px-4 py-3">Product id</th>
              <th scope="col" class="px-4 py-3">Product name</th>
              <th scope="col" class="px-4 py-3">Category</th>
              <th scope="col" class="px-4 py-3">Code</th>
              <th scope="col" class="px-4 py-3">Description</th>
              <th scope="col" class="px-4 py-3">Price</th>
              <th scope="col" class="px-4 py-3">
                <span class="sr-only">Actions</span>
              </th>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr class="border-b border-gray-500">
                <td class="px-4 py-3"> <%= product.id %> </td>
                <th scope="row" class="px-4 py-3 font-medium whitespace-nowrap"><%= product.name %></th>
                <td class="px-4 py-3"> <%= product['category_name'] %> </td>
                <td class="px-4 py-3"><%= product.code %></td>
                <td class="px-4 py-3"><%= truncate(product.description, length: 50) %></td>
                <td class="px-4 py-3"><%= product.price %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="text-xl ml-10 mt-3 bg-gray-600 text-white border rounded-lg w-max p-2">
    <%= paginate @products %>
  </div>
</section>

app/views/products/new.html.erb
<div class="w-full absolute left-[25%] top-[200px]">
  <div class="">
    <p class="text-2xl mb-2">Sample Template</p>
    <%= link_to "Click here to download sample template", "/product_template/sample_template.xlsx",class:"underline" %>
  </div>
  <div class="border rounded-md h-[200px] bg-gray-300 w-1/2 p-5 mt-10">
    <p class="text-2xl pb-10">Upload products through xlsx or csv file</p>
    <%= form_with url: import_products_path, method: :post, multipart: true do |form| %>
      <%= form.file_field :file, required: true %>
      <%= form.submit "Upload Products", class:"p-2 cursor-pointer rounded-md bg-gray-600 text-white hover:bg-gray-800" %>
    <% end %>
  </div>
</div>